# Generated by Django 4.0.2 on 2022-09-13 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_alter_album_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='description_cn',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='album',
            name='description_en',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='album',
            name='subtitle_cn',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='album',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='album',
            name='title_cn',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='album',
            name='title_en',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
