# Generated by Django 4.0.2 on 2022-09-13 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0005_album_description_cn_album_description_en_and_more'),
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='description_cn',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='photo',
            name='description_en',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='photo',
            name='subtitle_cn',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='photo',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='photo',
            name='title_cn',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='photo',
            name='title_en',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='photo',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='album.album'),
        ),
    ]
